export const spanishLogos: Record<string, string> = {
  Alaves: '/clubs/es-96.v1.png',
  'Athletic Bilbao': '/clubs/es-93.v1.png',
  'Atletico Madrid': '/clubs/es-1068.v1.png',
  Barcelona: '/clubs/es-83.v1.png',
  Celta: '/clubs/es-85.v1.png',
  'Deportivo La Coruna': '/clubs/es-90.v1.png',
  Elche: '/clubs/es-3751.v1.png',
  Espanyol: '/clubs/es-88.v1.png',
  Getafe: '/clubs/es-2922.v1.png',
  Levante: '/clubs/es-1538.v1.png',
  Malaga: '/clubs/es-99.v1.png',
  Osasuna: '/clubs/es-97.v1.png',
  'Racing Santander': '/clubs/es-87.v1.png',
  'Rayo Vallecano': '/clubs/es-101.v1.png',
  Betis: '/clubs/es-244.v1.png',
  'Real Madrid': '/clubs/es-86.v1.png',
  'Real Sociedad': '/clubs/es-89.v1.png',
  Sevilla: '/clubs/es-243.v1.png',
  Valencia: '/clubs/es-94.v1.png',
  Villarreal: '/clubs/es-102.v1.png',
};
